language: ruby
rvm:
  - ruby-head
  - 2.6.3
  - 2.5.5
  - 2.4.6
before_install:
  - gem update --system
install:
  - bundle install --without development
script:
  - bundle exec rspec
env:
  global:
  - secure: mYLlt3vNvom0gio06mDeEYjm7t4N8+KACtgw0OCfxt2tfXAxyATX5CtCyFo8zbUoQ2XazHJJT8czH4OkT3EeG0X8ZLCSNF9Zi5n0OGLX4gZhwkoe6/opd9bMuarS7UqGJFQ+m1YeNsw3RXlBdyO9MsC3M3CSvSlzeaVHxsYD7tzkO+BoLQ8E8o/dcTaYiOoISf2dOMCphs4NSeAvG7ihG3Jr0SJ6kkZFZcf823zLPYg/DpMUEpB+AlZ5n6R1PrZFLoLa3VEobsjxqeftzo6xwXq1/ZAdnBqgnJV1TY901kAhmbmPWzdbvYUUJOjJKMjweR8TbdCRwpvT88wGsit5Myy6Y1KPR8ssB7XhssNCXZz6x7ydKPbFSN0LAhIWEYcKmw8LJoTVzqcBPG6sGpvjDJQiln3z5e3qgJod5NUt3i+IVV/eQHbN8IepXS1Atjg2Ql7sbk5yYtM9jk3H5+PlqsxEaH8eZLw7Ho0uRJv+9KPWRsCDrwkAa2+n3F06Ld+CtWFa7vfH08eHAZ/yfOtbvXeW2Hs1AxNpyfS9wKzrF2cGcLUU5pc0P8Yl7ByA5yUMX3SDEMYGZBIAGbVlJgN1TNhcDbQRuUgcd4gBYdV/LAgkNh9x3kL39JtypDHEI5buwrqfU25AQvP7oSP9ZCJj1aPS0fRqApSU6pNsxx88z80=
  - secure: dpZNZ3DiwctpX4hJ1r6BlPF9KXiz2ysBP+uOVyIMYgt2jSSKyZ9gU55Xcb+UM3lFmeUrqOuKAhbUw3rQnBlVEqT+/xLA4XzE5dEe9d4O0DmF5qoEloHV/JL7QZgm/xAxuZ/iFSbQVCsu2wJezNH8nrYh7kVZ176yPo/IQHDQhdxxFTvHC3b2fFUibNKcZxB4cbseIEO2bghqjmM5Y7f8RRf+qm6SqZc21MMuOZ0WdVtzSnNImalohBfMFmLE4OYMg7Rxoyg2luwRP8TKWrQ3+DYVsIHVW1f3NDIQWlhPXfNjIa1X4LXeTTG9LwcNfm9d29ROXDdExbtGMBKzmHuV2QKTr/oi4dIX/kFTkf88RhVlVHA7W8Nwm1u9QlhldhfO7MFF/oze7fZk+sezPTH2yJYXIcldyD0QNDYLshUbh6g9450CljmKXFENpUWQATnJO8sBC3VaW98ummfqHkNfTNTNi+ZXO4NYLqORez2VEBziKknqHmux/X2KHVesBF/pjcNwnyjWdca4szBL8knv1ZuIwAusAEunNRfDJJ7I7JDOFhC4tWgF+8EDCTermffxDApNDcHIzAU3fXTBq24u43xRCvV4qHWGdtIQ6qBvYaC4+t7MyQk0ym4e6uD6zwxvr5Ksm98WaE9nGi1uCJNUA7BFiiV5mqaqT+yfjl4s9cM=
