language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
matrix:
  allow_failures:
    - rvm: ruby-head
install:
  - gem update bundler
  - bundle install --without development
script:
  - bundle exec rspec
env:
  global:
  - secure: iOsTdW8VTKm6sqWB+MMlYkxhKx2ZRatvchs99XLYqhOAHzwd3X+vacC0CMnv6Sk2OrCDc0cDsvUwpZF0p42BUaNMYTbRwp1vcYmaCRrg5ETVSSNdEOq7LRUFdMzfORr95KCf/HWkhFmV0iXaJTDhj62Zvza9kTANJ4+GE+XN8jM1ymK2JLjD781JPJrJWnZC5iEaEgEQTizrnlCAr4kPhfj7skgowCgPVPHxk5NxC3GUJzlXiOfihEyPHmTY0pSQwaSjFugfnQYtbenexL6YsV2mMDAgH85QrOE5CqxzsNyziQRVr5sCGZbdb+FiX1pnT23QzffvFDkyiXAxy2sf8WY5+S3+yMvkSO0fbbprlHHr/uUnX0u9y40hf9HD3dZFgPDJY+XBVxiO0rbQUW1pJ17gOi1RZO8skeXy+kkIRBEhQJDw18ds66dkEoeQ0aK/+V9crTmFUE61/kPhRtPdjKhCOlphJzJhnYmbCLfaSIGzvlwvkytL+GTHA5OzHyMiH8xrZdc/YuhZ8YgMtG/QN2eVLL/oSyTTp3u/r/4Kzz8Svz1prOSW1ieNJQ7MI4Ld0Mh9mnyeEyKfYWuP7Ip8yQbow5jkIUaRXpuBsagRk3iEwH2BrgOxOjGKJ91UyYdeUX5LRqJlC0tqUlqeaA1c1W9Tq/wI1FORd4a1hkQ01bE=
  - secure: frzfWSVE8HpH8nmzeOoCbMWgmMyzBs4ohqxvoqTd7nc4e0XQLsTef0K3moescCYI0I5IkucrdFc4q4A3nIu9W+xezWR8qjr40gz4EPtuP+MZP2izCWmPI574v3LrIAX9zyoqdlYHi2brGi1fUjqrYWA5UGm5fZW21NUBfsg3xOVS8M9JqdlIpDwveSW67VghVDu6pb6ax2QSoo0dmtV4WJq1DN9gZmD6oAtWESQD7A8awAplWLinLOqzLqH/zucznmx5rnccbC1DztvRq5z2YLee13uZmz7dL6Jp/P9f1u7G4KOZJ7irKHKPkvt30D33UYzcpQ5jF1hyoz4PZ8+9ywbjsnkOGWXGYgqMwULELma24AQcx+JUmhr6PjKp0//PcPTE4Q+4l1cX1Yx2Ie9jzO2mkkLpBE9lb/XI75QSI3PrfJDEMXkp5tRi63f3IgrKW0DQ0mtJVANfA8siFSf8uiV9rZV31AMlXOUKjOrzEr0Szd+fmLZzGHVIbrfSXSQdQ3GDAyRmPIC6nL+pFwnXgCljDoWscgKsjtr5d9lUmSqmGgn2+cIjiy/TUvvl1DtAoTxT3sp5iwREsMygK2KQ6u6Xbf3BNlnCRpZY6HylzGIB1EwOyJT/b62y/aHhuwhsyaMhlo5UYEbNYF4+7yVc5e4ZsX9pqNKzRmpL4llJr4Y=
